### ISSUE TITLE
Add documentation for custom field presentation

### ISSUE THREAD

**Issue by alenoosh** [serverfireteam/panel#76]
For example how to display images in crud list.

**Comment by warksit** [comment]
Any pointers on this?

**Comment by serverfire** [comment]
are we talking about http://laravelpanel.com/docs/master/crud-custom-fields ?

**Comment by warksit** [comment]
I'm not sure. What I was trying to achieve is displaying link (for which the href is a Model Accessor) for each record on an 'all' page. So just about display rather than edit.

The ultimate issue I am trying to solve is I am using a file field to upload a pdf which I move to a folder within storage. However the link shown doesn't work as storage is not publicly accessible.

**Comment by serverfire** [comment]
you could have that , just read the Zofe\Rapyd document and edit the view of list to add view ,

for your other problem , write a route and give access to storage
