### ISSUE TITLE
edit_url_table migration causes error on new installations

### ISSUE THREAD

**Issue by DeftNerd** [serverfireteam/panel#8]
The edit_url_table migration causes an error on new migrations because the links table is already seeded with a default link. When the migration runs, Laravel attempts to create a new "main" column and set the value to NULL but the migration doesn't mark the field being created as nullable, resulting in the error. 

You can fix this by editing the 2015_03_15_123956_edit_url_table.php file to perform:
$table->boolean('main')->nullable();

instead of 
$table->boolean('main');

**Comment by alenoosh** [comment]
@DeftNerd please mention the version of panel you have downloaded and also the exact error message you get. 
Because we don't have this error in the latest version and if you have downloaded a previous version of panel, after updating it and running the panel:install command, the 'main' filed is added and set  for the existing records in 'links' table.

**Comment by alenoosh** [comment]
@DeftNerd You were right about this bug, I got this error while testing our package with sqlite. I was testing with mysql before. I have fixed the bug. Thanks alot for reporting it.
